#!/bin/sh

#--------------------------------------------------------------------------
# Copyright 2021 Greifent
# https://github.com/Greifent/afc-gui
#--------------------------------------------------------------------------

echo 'making directories'
mkdir /usr/share/afc-gui-gtk3


echo 'copying files'
cp src/afc-gui-gtk3 /usr/bin
cp src/MAINGUI.glade /usr/share/afc-gui-gtk3
cp src/afc-gui-gtk3.desktop /usr/share/applications
