#!/bin/sh

#--------------------------------------------------------------------------
# Copyright 2021 Greifent
# https://github.com/Greifent/afc-gui
#--------------------------------------------------------------------------

echo 'making directories'
mkdir /usr/share/afc-gui

echo 'copying files'
cp src/afc-gui /usr/bin
cp src/MAINGUI.glade /usr/share/afc-gui
cp src/afc-gui.desktop /usr/share/applications
