#!/bin/sh

#--------------------------------------------------------------------------
# Copyright 2021 Greifent
# https://github.com/Greifent/afc-gui
#--------------------------------------------------------------------------

echo 'removing files and directories'
rm /usr/bin/afc-gui-gtk3
rm -r /usr/share/afc-gui-gtk3
rm /usr/share/applications/afc-gui-gtk3.desktop
